#include <iostream>
#include<stdlib.h>
#include<time.h>
using namespace std;
class guessnum
{
    public:
    int n;//number generated by the comp
    guessnum()
    {
        srand((long int)clock());//helps generate diff num on eacg generation
        n=rand()%100;//generate random number from 0 to 100
    }
    
    bool feedback(int num)
    {
        if(num==n)
        {
            cout<<"Congrats!!! the number has been found------"<<n<<endl;
            return true;//number has been guessed correctly
        }
        if(num>n)
        {
            cout<<"The number is a lower value-----why not try guessing again??"<<endl;
        }
        if(num<n)
        {
             cout<<"The number is a higher value-----why not try guessing again??"<<endl;
        }
        return false;//number not guessed correctly
    }
};

int main()
{
    int num,f;
    guessnum g;
    cout<<"Welcome to the number guessing game!!"<<endl<<"The rules are simple.....try to guess the number generated by the computer(the number is bet 0 and 100)"<<endl;
    cout<<"Enter ur first guess:"<<endl;
    cin>>num;
    f=g.feedback(num);
    if(f)
    return 0;
    while(!f)
    {
     cout<<"Enter ur nxt guess:"<<endl;
    cin>>num;
    f=g.feedback(num);
    }
}
